### ISSUE TITLE
Add code used to compile the binaries

### ISSUE THREAD

**Issue by josegonzalez** [schmurtzm/MiyooMini_Tools#2]
It would be great to add any code/commands used to compile the libraries so that others can easily compile their own versions in the future (or that we can try and automate it in CI for testing purposes).

**Comment by schmurtzm** [comment]
This is a repo of compiled tools from the community (not all from mine at all). Most of the tools doesn't contain the sources because it comes from the main code source without modification and default compilation parameters.
However you have probably seen that when it's easily possible I have incorporated the source code.
Feel free to complete these with PR, it is collaborative and I would be happy to have help on this centralisation  ;)

**Comment by josegonzalez** [comment]
No worries, didn't realize they were community compiled.

I'll close for now as there isn't anything to do :)
